# Generated by Django 5.2.17 on 2026-09-28 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField()),
                ('claimed_code', models.CharField(max_length=64)),
                ('roster_version', models.CharField(max_length=80)),
                ('policy_version', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('STARTED', 'Đã bắt đầu'), ('IN_PROGRESS', 'Đang kiểm tra'), ('REVIEW_PENDING', 'Chờ xử lý'), ('CONCLUDED', 'Đã kết luận'), ('INTERRUPTED', 'Bị gián đoạn')], default='STARTED', max_length=16)),
                ('lookup_outcome', models.CharField(choices=[('PENDING', 'Chưa tra cứu'), ('FOUND', 'Một hồ sơ'), ('NOT_FOUND', 'Không tìm thấy'), ('AMBIGUOUS', 'Nhiều hồ sơ'), ('WRONG_ROOM', 'Sai phòng')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntakeContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_version', models.CharField(blank=True, max_length=80)),
                ('roster_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('policy_version', models.CharField(blank=True, max_length=80)),
                ('policy_approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_role', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('SETUP', 'Đang chuẩn bị'), ('OPEN', 'Đang tiếp nhận'), ('CLOSED', 'Đã đóng')], default='SETUP', max_length=8)),
                ('policy_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_intake_policies', to=settings.AUTH_USER_MODEL)),
                ('roster_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_rosters', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entry.examsession')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entry.room')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ATTEMPT_STARTED', 'Bắt đầu lượt'), ('LOOKUP_RESOLVED', 'Tìm thấy hồ sơ'), ('REVIEW_OPENED', 'Mở ngoại lệ')], max_length=24)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entry.attempt')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entry.intakecontext')),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entry.intakecontext'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_version', models.CharField(max_length=80)),
                ('source_key', models.CharField(max_length=120)),
                ('candidate_code', models.CharField(max_length=64)),
                ('display_label', models.CharField(blank=True, max_length=120)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entry.examsession')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entry.room')),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='entry.registration'),
        ),
        migrations.CreateModel(
            name='ReviewCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('NOT_FOUND', 'Không tìm thấy hồ sơ'), ('AMBIGUOUS', 'Hồ sơ mơ hồ'), ('WRONG_ROOM', 'Sai phòng')], max_length=12)),
                ('status', models.CharField(choices=[('OPEN', 'Đang mở'), ('RESOLVED', 'Đã xử lý')], default='OPEN', max_length=8)),
                ('assigned_role', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review_case', to='entry.attempt')),
            ],
        ),
        migrations.CreateModel(
            name='ContextAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OPERATOR', 'Vận hành'), ('REVIEWER', 'Xử lý ngoại lệ')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='entry.intakecontext')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'context', 'role'), name='one_grant_per_user_context_role')],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='entry.attempt')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entry.examsession')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entry.registration')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'registration'), name='one_effective_checkin_per_session')],
            },
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('context', 'idempotency_key'), name='unique_attempt_request_per_context'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['session', 'roster_version', 'candidate_code'], name='registration_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('session', 'roster_version', 'source_key'), name='unique_roster_source_record'),
        ),
        migrations.AddConstraint(
            model_name='intakecontext',
            constraint=models.UniqueConstraint(fields=('session', 'room'), name='one_context_per_session_room'),
        ),
        migrations.AddConstraint(
            model_name='intakecontext',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'OPEN'), _negated=True), models.Q(models.Q(('roster_version', ''), _negated=True), ('roster_confirmed_at__isnull', False), ('roster_confirmed_by__isnull', False), models.Q(('policy_version', ''), _negated=True), ('policy_approved_at__isnull', False), ('policy_approved_by__isnull', False), models.Q(('review_role', ''), _negated=True)), _connector='OR'), name='open_context_has_readiness_references'),
        ),
    ]
